### PR TITLE
Update ReadME.md

### PR DESCRIPTION
**Pull request by aananthraj**
Updated docker run command for starting kubewatch container.

**Description of the change**

Changes the Docker Run command to make it work in local without config errors

**Benefits**

User can directly start the container without config errors

**Possible drawbacks**

nil

**Applicable issues**

nil

**Additional information**

### CODE REVIEW

**Comment by aananthraj** [comment]
Thanks @jjo for the prompt responce. Do update this command in docker hub repository as well.

And it would be helpful, if you could review the pending PRs in kubewatch repo.

**Comment by aananthraj** [comment]
Can this be merged..?

**Comment by juan131** [comment]
Merging your PR @aananthraj ! Thanks for your contribution

**Comment by aananthraj** [comment]
Thanks @juan131 :+1:

**Comment by aananthraj** [comment]
@juan131 the changes submitted in the PR is not available now,
Look like bitnami bot has deleted the changes made.

Do have a look at the reference mentioned below
https://github.com/bitnami/bitnami-docker-kubewatch/commit/6aae2ac20f40668ba719df452269bfc5e476ab54#r34271465

**Comment by carrodher** [comment]
@aananthraj I just added the changes into our CI/CD, in this way the next daily release will contain it. In the same wait, I added it to GitHub right now.

Thanks for reporting it!

**Comment by aananthraj** [comment]
Thanks @carrodher.

Can we have the latest code changes available in bitnami-labs/kubewatch repo as a 0.0.5-alpha image in bitnami/kubewatch docker hub repository with automated build.

This could enable the use of latest code, instead of waiting for next minor release.
For instance code changes for #5 is available in github repo but not as a docker image.

**Comment by carrodher** [comment]
Hi, unfortunately, they are decoupled processes.

In one hand we have the https://github.com/bitnami-labs/kubewatch project where the code is hosted, releases are managed, etc and in the other hand, there is this repository where the Dockerfiles are pushed daily (with some updates as we talked in other thread).

Although the [kubewatch](https://github.com/bitnami-labs/kubewatch) project is maintained by Bitnami, there is not much relation between this repo and the [kubewatch](https://github.com/bitnami-labs/kubewatch) project, we only track [kubewatch](https://github.com/bitnami-labs/kubewatch) releases and generate the Docker images, in the same way that we provide Docker images for [WordPress](https://github.com/bitnami/bitnami-docker-wordpress), [Drupal](https://github.com/bitnami/bitnami-docker-drupal), etc but we don't have control over the application releases.

As a separate issue, [kubewatch](https://github.com/bitnami-labs/kubewatch) is not actively maintained at this moment but we do not like this situation, so we are planning to revisit the project in the short/middle term.

**Comment by aananthraj** [comment]
Thanks @carrodher.

> As a separate issue, kubewatch is not actively maintained at this moment but we do not like this situation, so we are planning to revisit the project in the short/middle term.

Waiting for it 👍

I have raised several PRs in kubewatch repo and waiting for getting it reviewed.
Any help from your side will be appriciated. Hope you people jump in soon.

**Pull request merged**
